dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y portaudio19-dev

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - python setup.py test

deploy:
  provider: pypi
  user: yuma-m
  password:
    secure: qjpVeA6X06tcuOtaFqoVD9fnbxRW4OGRrP/0bIqCdxj9HoDBPCJkgvcxVSrAzB+4ejsPPvIuqBdtnbcCkYmq+tpsK2Gh8HVU/XBSE0jF4luwKgMvHIh0WxsxgtWjft0tlD14kfGES5zIOyd3Jqz7f7BA+tg+jIn16eysEjysphM2rzlorQdiDfvtvILJZ7NvuCPvV4XD+vVdzzJll5f8Ps9F/Y/F9/nvFjXK1c5+OOrc47o3i/0fA711dcw9h4oho9CNcp904gaEiwtOxTGkAAuxlHSqiD1/aZ3XHKnmEyV00UZlndZXNFjhEqXoGi7QZihO3B0Zf4FbMvydSRzEuPUgqoVaNkLwDN6vr2m9RU9Z8VnkUwgOlqp3QlHF7sOSd1BtjgAmCdctdzjWlHDxwnytP4mgcZsHLb+LHs7k6k2KUtnp7TX2F9EDP/I2u+g3SrgbORkOec0ULFyih4pIhGrGfNwRFVnwaRWRiHGvEpo1GG3EQ+UKJt+o4MEmR23ZSXm2/gOZmpO9sFf/bJsXEm79VSGcmgm3Lxe5Lzdz2GJKFhTZE2VtVrHBY95Uy8TVZPPy1KmrjFEqcoh0Kix5+s0p9oNs+6gpqYpRR5PJOWtK53fyvw/2NQAmeNJ3DTEmfrtbXFiDM4ud8tmt76DxIaJV3jlTvFF8Og27tkwHNxU=
  on:
    python: 3.6
    tags: true
